source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'TFFallLayout_Example' do
  pod 'TFFallLayout', :path => '../'
  pod 'Masonry'
  target 'TFFallLayout_Tests' do
    inherit! :search_paths

    
  end
end
